/*
 * Generated by gdbus-codegen 2.58.3 from com.lingmo.daemon.Authenticate.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __COM_DEEPIN_DAEMON_AUTHENTICATE_H__
#define __COM_DEEPIN_DAEMON_AUTHENTICATE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.deepin.daemon.Authenticate */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE (com_deepin_daemon_authenticate_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE, ComDeepinDaemonAuthenticate))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE, ComDeepinDaemonAuthenticateIface))

struct _ComDeepinDaemonAuthenticate;
typedef struct _ComDeepinDaemonAuthenticate ComDeepinDaemonAuthenticate;
typedef struct _ComDeepinDaemonAuthenticateIface ComDeepinDaemonAuthenticateIface;

struct _ComDeepinDaemonAuthenticateIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_authenticate) (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType);

  gboolean (*handle_get_limits) (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_username);

  gboolean (*handle_pre_one_key_login) (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag);

  gint  (*get_framework_state) (ComDeepinDaemonAuthenticate *object);

  const gchar * (*get_support_encrypts) (ComDeepinDaemonAuthenticate *object);

  gint  (*get_supported_flags) (ComDeepinDaemonAuthenticate *object);

  void (*limit_updated) (
    ComDeepinDaemonAuthenticate *object,
    const gchar *arg_username);

};

GType com_deepin_daemon_authenticate_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_deepin_daemon_authenticate_interface_info (void);
guint com_deepin_daemon_authenticate_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_deepin_daemon_authenticate_complete_authenticate (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *path);

void com_deepin_daemon_authenticate_complete_get_limits (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *limits);

void com_deepin_daemon_authenticate_complete_pre_one_key_login (
    ComDeepinDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *result);



/* D-Bus signal emissions functions: */
void com_deepin_daemon_authenticate_emit_limit_updated (
    ComDeepinDaemonAuthenticate *object,
    const gchar *arg_username);



/* D-Bus method calls: */
void com_deepin_daemon_authenticate_call_authenticate (
    ComDeepinDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_call_authenticate_finish (
    ComDeepinDaemonAuthenticate *proxy,
    gchar **out_path,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_call_authenticate_sync (
    ComDeepinDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType,
    gchar **out_path,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_call_get_limits (
    ComDeepinDaemonAuthenticate *proxy,
    const gchar *arg_username,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_call_get_limits_finish (
    ComDeepinDaemonAuthenticate *proxy,
    gchar **out_limits,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_call_get_limits_sync (
    ComDeepinDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gchar **out_limits,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_call_pre_one_key_login (
    ComDeepinDaemonAuthenticate *proxy,
    gint arg_flag,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_call_pre_one_key_login_finish (
    ComDeepinDaemonAuthenticate *proxy,
    gchar **out_result,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_call_pre_one_key_login_sync (
    ComDeepinDaemonAuthenticate *proxy,
    gint arg_flag,
    gchar **out_result,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *com_deepin_daemon_authenticate_get_support_encrypts (ComDeepinDaemonAuthenticate *object);
gchar *com_deepin_daemon_authenticate_dup_support_encrypts (ComDeepinDaemonAuthenticate *object);
void com_deepin_daemon_authenticate_set_support_encrypts (ComDeepinDaemonAuthenticate *object, const gchar *value);

gint com_deepin_daemon_authenticate_get_framework_state (ComDeepinDaemonAuthenticate *object);
void com_deepin_daemon_authenticate_set_framework_state (ComDeepinDaemonAuthenticate *object, gint value);

gint com_deepin_daemon_authenticate_get_supported_flags (ComDeepinDaemonAuthenticate *object);
void com_deepin_daemon_authenticate_set_supported_flags (ComDeepinDaemonAuthenticate *object, gint value);


/* ---- */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY (com_deepin_daemon_authenticate_proxy_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY, ComDeepinDaemonAuthenticateProxy))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY, ComDeepinDaemonAuthenticateProxyClass))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY, ComDeepinDaemonAuthenticateProxyClass))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_PROXY))

typedef struct _ComDeepinDaemonAuthenticateProxy ComDeepinDaemonAuthenticateProxy;
typedef struct _ComDeepinDaemonAuthenticateProxyClass ComDeepinDaemonAuthenticateProxyClass;
typedef struct _ComDeepinDaemonAuthenticateProxyPrivate ComDeepinDaemonAuthenticateProxyPrivate;

struct _ComDeepinDaemonAuthenticateProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComDeepinDaemonAuthenticateProxyPrivate *priv;
};

struct _ComDeepinDaemonAuthenticateProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_deepin_daemon_authenticate_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComDeepinDaemonAuthenticateProxy, g_object_unref)
#endif

void com_deepin_daemon_authenticate_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComDeepinDaemonAuthenticate *com_deepin_daemon_authenticate_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComDeepinDaemonAuthenticate *com_deepin_daemon_authenticate_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_deepin_daemon_authenticate_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComDeepinDaemonAuthenticate *com_deepin_daemon_authenticate_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComDeepinDaemonAuthenticate *com_deepin_daemon_authenticate_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON (com_deepin_daemon_authenticate_skeleton_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON, ComDeepinDaemonAuthenticateSkeleton))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON, ComDeepinDaemonAuthenticateSkeletonClass))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON, ComDeepinDaemonAuthenticateSkeletonClass))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SKELETON))

typedef struct _ComDeepinDaemonAuthenticateSkeleton ComDeepinDaemonAuthenticateSkeleton;
typedef struct _ComDeepinDaemonAuthenticateSkeletonClass ComDeepinDaemonAuthenticateSkeletonClass;
typedef struct _ComDeepinDaemonAuthenticateSkeletonPrivate ComDeepinDaemonAuthenticateSkeletonPrivate;

struct _ComDeepinDaemonAuthenticateSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComDeepinDaemonAuthenticateSkeletonPrivate *priv;
};

struct _ComDeepinDaemonAuthenticateSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_deepin_daemon_authenticate_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComDeepinDaemonAuthenticateSkeleton, g_object_unref)
#endif

ComDeepinDaemonAuthenticate *com_deepin_daemon_authenticate_skeleton_new (void);


G_END_DECLS

#endif /* __COM_DEEPIN_DAEMON_AUTHENTICATE_H__ */
