/*
 * Generated by gdbus-codegen 2.58.3 from com.lingmo.daemon.Authenticate.Session.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_H__
#define __COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.lingmo.daemon.Authenticate.Session */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION (com_lingmo_daemon_authenticate_session_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION, ComLingmoDaemonAuthenticateSession))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION, ComLingmoDaemonAuthenticateSessionIface))

struct _ComLingmoDaemonAuthenticateSession;
typedef struct _ComLingmoDaemonAuthenticateSession ComLingmoDaemonAuthenticateSession;
typedef struct _ComLingmoDaemonAuthenticateSessionIface ComLingmoDaemonAuthenticateSessionIface;

struct _ComLingmoDaemonAuthenticateSessionIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_encrypt_key) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_encryptType,
    GVariant *arg_encryptMethod);

  gboolean (*handle_end) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag);

  gboolean (*handle_get_result) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_privileges_disable) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_privileges_enable) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_masterPath);

  gboolean (*handle_quit) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_quit_flag) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_method);

  gboolean (*handle_set_symmetric_key) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_key);

  gboolean (*handle_set_token) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag,
    GVariant *arg_token);

  gboolean (*handle_start) (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag,
    gint arg_timeout);

  GVariant * (*get_factors_info) (ComLingmoDaemonAuthenticateSession *object);

  gboolean  (*get_is_mfa) (ComLingmoDaemonAuthenticateSession *object);

  gint  (*get_pinlen) (ComLingmoDaemonAuthenticateSession *object);

  const gchar * (*get_prg_path) (ComLingmoDaemonAuthenticateSession *object);

  const gchar * (*get_prompt) (ComLingmoDaemonAuthenticateSession *object);

  const gchar * (*get_username) (ComLingmoDaemonAuthenticateSession *object);

  void (*status) (
    ComLingmoDaemonAuthenticateSession *object,
    gint arg_flag,
    gint arg_status,
    const gchar *arg_msg);

};

GType com_lingmo_daemon_authenticate_session_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_lingmo_daemon_authenticate_session_interface_info (void);
guint com_lingmo_daemon_authenticate_session_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_lingmo_daemon_authenticate_session_complete_encrypt_key (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint encType,
    GVariant *encMethod,
    const gchar *pubKey);

void com_lingmo_daemon_authenticate_session_complete_end (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint failNum);

void com_lingmo_daemon_authenticate_session_complete_get_result (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint result);

void com_lingmo_daemon_authenticate_session_complete_privileges_disable (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_lingmo_daemon_authenticate_session_complete_privileges_enable (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gboolean enabled);

void com_lingmo_daemon_authenticate_session_complete_quit (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_lingmo_daemon_authenticate_session_complete_set_quit_flag (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_lingmo_daemon_authenticate_session_complete_set_token (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_lingmo_daemon_authenticate_session_complete_start (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint failNum);

void com_lingmo_daemon_authenticate_session_complete_set_symmetric_key (
    ComLingmoDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void com_lingmo_daemon_authenticate_session_emit_status (
    ComLingmoDaemonAuthenticateSession *object,
    gint arg_flag,
    gint arg_status,
    const gchar *arg_msg);



/* D-Bus method calls: */
void com_lingmo_daemon_authenticate_session_call_encrypt_key (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_encryptType,
    GVariant *arg_encryptMethod,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_encrypt_key_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint *out_encType,
    GVariant **out_encMethod,
    gchar **out_pubKey,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_encrypt_key_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_encryptType,
    GVariant *arg_encryptMethod,
    gint *out_encType,
    GVariant **out_encMethod,
    gchar **out_pubKey,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_end (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_end_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint *out_failNum,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_end_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint *out_failNum,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_get_result (
    ComLingmoDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_get_result_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_get_result_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_privileges_disable (
    ComLingmoDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_privileges_disable_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_privileges_disable_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_privileges_enable (
    ComLingmoDaemonAuthenticateSession *proxy,
    const gchar *arg_masterPath,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_privileges_enable_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    gboolean *out_enabled,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_privileges_enable_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    const gchar *arg_masterPath,
    gboolean *out_enabled,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_quit (
    ComLingmoDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_quit_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_quit_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_set_quit_flag (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_method,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_set_quit_flag_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_set_quit_flag_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_method,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_set_token (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GVariant *arg_token,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_set_token_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_set_token_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GVariant *arg_token,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_start (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint arg_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_start_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint *out_failNum,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_start_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint arg_timeout,
    gint *out_failNum,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_session_call_set_symmetric_key (
    ComLingmoDaemonAuthenticateSession *proxy,
    GVariant *arg_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_session_call_set_symmetric_key_finish (
    ComLingmoDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_session_call_set_symmetric_key_sync (
    ComLingmoDaemonAuthenticateSession *proxy,
    GVariant *arg_key,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean com_lingmo_daemon_authenticate_session_get_is_mfa (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_is_mfa (ComLingmoDaemonAuthenticateSession *object, gboolean value);

const gchar *com_lingmo_daemon_authenticate_session_get_prompt (ComLingmoDaemonAuthenticateSession *object);
gchar *com_lingmo_daemon_authenticate_session_dup_prompt (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_prompt (ComLingmoDaemonAuthenticateSession *object, const gchar *value);

GVariant *com_lingmo_daemon_authenticate_session_get_factors_info (ComLingmoDaemonAuthenticateSession *object);
GVariant *com_lingmo_daemon_authenticate_session_dup_factors_info (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_factors_info (ComLingmoDaemonAuthenticateSession *object, GVariant *value);

const gchar *com_lingmo_daemon_authenticate_session_get_username (ComLingmoDaemonAuthenticateSession *object);
gchar *com_lingmo_daemon_authenticate_session_dup_username (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_username (ComLingmoDaemonAuthenticateSession *object, const gchar *value);

gint com_lingmo_daemon_authenticate_session_get_pinlen (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_pinlen (ComLingmoDaemonAuthenticateSession *object, gint value);

const gchar *com_lingmo_daemon_authenticate_session_get_prg_path (ComLingmoDaemonAuthenticateSession *object);
gchar *com_lingmo_daemon_authenticate_session_dup_prg_path (ComLingmoDaemonAuthenticateSession *object);
void com_lingmo_daemon_authenticate_session_set_prg_path (ComLingmoDaemonAuthenticateSession *object, const gchar *value);


/* ---- */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY (com_lingmo_daemon_authenticate_session_proxy_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY, ComLingmoDaemonAuthenticateSessionProxy))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY, ComLingmoDaemonAuthenticateSessionProxyClass))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY, ComLingmoDaemonAuthenticateSessionProxyClass))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_PROXY))

typedef struct _ComLingmoDaemonAuthenticateSessionProxy ComLingmoDaemonAuthenticateSessionProxy;
typedef struct _ComLingmoDaemonAuthenticateSessionProxyClass ComLingmoDaemonAuthenticateSessionProxyClass;
typedef struct _ComLingmoDaemonAuthenticateSessionProxyPrivate ComLingmoDaemonAuthenticateSessionProxyPrivate;

struct _ComLingmoDaemonAuthenticateSessionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComLingmoDaemonAuthenticateSessionProxyPrivate *priv;
};

struct _ComLingmoDaemonAuthenticateSessionProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_lingmo_daemon_authenticate_session_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLingmoDaemonAuthenticateSessionProxy, g_object_unref)
#endif

void com_lingmo_daemon_authenticate_session_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLingmoDaemonAuthenticateSession *com_lingmo_daemon_authenticate_session_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComLingmoDaemonAuthenticateSession *com_lingmo_daemon_authenticate_session_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_lingmo_daemon_authenticate_session_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLingmoDaemonAuthenticateSession *com_lingmo_daemon_authenticate_session_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComLingmoDaemonAuthenticateSession *com_lingmo_daemon_authenticate_session_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON (com_lingmo_daemon_authenticate_session_skeleton_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComLingmoDaemonAuthenticateSessionSkeleton))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComLingmoDaemonAuthenticateSessionSkeletonClass))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComLingmoDaemonAuthenticateSessionSkeletonClass))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_SKELETON))

typedef struct _ComLingmoDaemonAuthenticateSessionSkeleton ComLingmoDaemonAuthenticateSessionSkeleton;
typedef struct _ComLingmoDaemonAuthenticateSessionSkeletonClass ComLingmoDaemonAuthenticateSessionSkeletonClass;
typedef struct _ComLingmoDaemonAuthenticateSessionSkeletonPrivate ComLingmoDaemonAuthenticateSessionSkeletonPrivate;

struct _ComLingmoDaemonAuthenticateSessionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComLingmoDaemonAuthenticateSessionSkeletonPrivate *priv;
};

struct _ComLingmoDaemonAuthenticateSessionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_lingmo_daemon_authenticate_session_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLingmoDaemonAuthenticateSessionSkeleton, g_object_unref)
#endif

ComLingmoDaemonAuthenticateSession *com_lingmo_daemon_authenticate_session_skeleton_new (void);


G_END_DECLS

#endif /* __COM_LINGMO_DAEMON_AUTHENTICATE_SESSION_H__ */
