/*
 * Generated by gdbus-codegen 2.58.3 from com.deepin.daemon.Authenticate.Session.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_H__
#define __COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.deepin.daemon.Authenticate.Session */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION (com_deepin_daemon_authenticate_session_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION, ComDeepinDaemonAuthenticateSession))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION, ComDeepinDaemonAuthenticateSessionIface))

struct _ComDeepinDaemonAuthenticateSession;
typedef struct _ComDeepinDaemonAuthenticateSession ComDeepinDaemonAuthenticateSession;
typedef struct _ComDeepinDaemonAuthenticateSessionIface ComDeepinDaemonAuthenticateSessionIface;

struct _ComDeepinDaemonAuthenticateSessionIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_encrypt_key) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_encryptType,
    GVariant *arg_encryptMethod);

  gboolean (*handle_end) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag);

  gboolean (*handle_get_result) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_privileges_disable) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_privileges_enable) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_masterPath);

  gboolean (*handle_quit) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_quit_flag) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_method);

  gboolean (*handle_set_symmetric_key) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_key);

  gboolean (*handle_set_token) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag,
    GVariant *arg_token);

  gboolean (*handle_start) (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag,
    gint arg_timeout);

  GVariant * (*get_factors_info) (ComDeepinDaemonAuthenticateSession *object);

  gboolean  (*get_is_mfa) (ComDeepinDaemonAuthenticateSession *object);

  gint  (*get_pinlen) (ComDeepinDaemonAuthenticateSession *object);

  const gchar * (*get_prg_path) (ComDeepinDaemonAuthenticateSession *object);

  const gchar * (*get_prompt) (ComDeepinDaemonAuthenticateSession *object);

  const gchar * (*get_username) (ComDeepinDaemonAuthenticateSession *object);

  void (*status) (
    ComDeepinDaemonAuthenticateSession *object,
    gint arg_flag,
    gint arg_status,
    const gchar *arg_msg);

};

GType com_deepin_daemon_authenticate_session_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_deepin_daemon_authenticate_session_interface_info (void);
guint com_deepin_daemon_authenticate_session_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_deepin_daemon_authenticate_session_complete_encrypt_key (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint encType,
    GVariant *encMethod,
    const gchar *pubKey);

void com_deepin_daemon_authenticate_session_complete_end (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint failNum);

void com_deepin_daemon_authenticate_session_complete_get_result (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint result);

void com_deepin_daemon_authenticate_session_complete_privileges_disable (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_deepin_daemon_authenticate_session_complete_privileges_enable (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gboolean enabled);

void com_deepin_daemon_authenticate_session_complete_quit (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_deepin_daemon_authenticate_session_complete_set_quit_flag (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_deepin_daemon_authenticate_session_complete_set_token (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);

void com_deepin_daemon_authenticate_session_complete_start (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation,
    gint failNum);

void com_deepin_daemon_authenticate_session_complete_set_symmetric_key (
    ComDeepinDaemonAuthenticateSession *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void com_deepin_daemon_authenticate_session_emit_status (
    ComDeepinDaemonAuthenticateSession *object,
    gint arg_flag,
    gint arg_status,
    const gchar *arg_msg);



/* D-Bus method calls: */
void com_deepin_daemon_authenticate_session_call_encrypt_key (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_encryptType,
    GVariant *arg_encryptMethod,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_encrypt_key_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint *out_encType,
    GVariant **out_encMethod,
    gchar **out_pubKey,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_encrypt_key_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_encryptType,
    GVariant *arg_encryptMethod,
    gint *out_encType,
    GVariant **out_encMethod,
    gchar **out_pubKey,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_end (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_end_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint *out_failNum,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_end_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint *out_failNum,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_get_result (
    ComDeepinDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_get_result_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint *out_result,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_get_result_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint *out_result,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_privileges_disable (
    ComDeepinDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_privileges_disable_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_privileges_disable_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_privileges_enable (
    ComDeepinDaemonAuthenticateSession *proxy,
    const gchar *arg_masterPath,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_privileges_enable_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    gboolean *out_enabled,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_privileges_enable_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    const gchar *arg_masterPath,
    gboolean *out_enabled,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_quit (
    ComDeepinDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_quit_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_quit_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_set_quit_flag (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_method,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_set_quit_flag_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_set_quit_flag_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_method,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_set_token (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GVariant *arg_token,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_set_token_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_set_token_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    GVariant *arg_token,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_start (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint arg_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_start_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint *out_failNum,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_start_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    gint arg_flag,
    gint arg_timeout,
    gint *out_failNum,
    GCancellable *cancellable,
    GError **error);

void com_deepin_daemon_authenticate_session_call_set_symmetric_key (
    ComDeepinDaemonAuthenticateSession *proxy,
    GVariant *arg_key,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_deepin_daemon_authenticate_session_call_set_symmetric_key_finish (
    ComDeepinDaemonAuthenticateSession *proxy,
    GAsyncResult *res,
    GError **error);

gboolean com_deepin_daemon_authenticate_session_call_set_symmetric_key_sync (
    ComDeepinDaemonAuthenticateSession *proxy,
    GVariant *arg_key,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean com_deepin_daemon_authenticate_session_get_is_mfa (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_is_mfa (ComDeepinDaemonAuthenticateSession *object, gboolean value);

const gchar *com_deepin_daemon_authenticate_session_get_prompt (ComDeepinDaemonAuthenticateSession *object);
gchar *com_deepin_daemon_authenticate_session_dup_prompt (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_prompt (ComDeepinDaemonAuthenticateSession *object, const gchar *value);

GVariant *com_deepin_daemon_authenticate_session_get_factors_info (ComDeepinDaemonAuthenticateSession *object);
GVariant *com_deepin_daemon_authenticate_session_dup_factors_info (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_factors_info (ComDeepinDaemonAuthenticateSession *object, GVariant *value);

const gchar *com_deepin_daemon_authenticate_session_get_username (ComDeepinDaemonAuthenticateSession *object);
gchar *com_deepin_daemon_authenticate_session_dup_username (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_username (ComDeepinDaemonAuthenticateSession *object, const gchar *value);

gint com_deepin_daemon_authenticate_session_get_pinlen (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_pinlen (ComDeepinDaemonAuthenticateSession *object, gint value);

const gchar *com_deepin_daemon_authenticate_session_get_prg_path (ComDeepinDaemonAuthenticateSession *object);
gchar *com_deepin_daemon_authenticate_session_dup_prg_path (ComDeepinDaemonAuthenticateSession *object);
void com_deepin_daemon_authenticate_session_set_prg_path (ComDeepinDaemonAuthenticateSession *object, const gchar *value);


/* ---- */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY (com_deepin_daemon_authenticate_session_proxy_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY, ComDeepinDaemonAuthenticateSessionProxy))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY, ComDeepinDaemonAuthenticateSessionProxyClass))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY, ComDeepinDaemonAuthenticateSessionProxyClass))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_PROXY))

typedef struct _ComDeepinDaemonAuthenticateSessionProxy ComDeepinDaemonAuthenticateSessionProxy;
typedef struct _ComDeepinDaemonAuthenticateSessionProxyClass ComDeepinDaemonAuthenticateSessionProxyClass;
typedef struct _ComDeepinDaemonAuthenticateSessionProxyPrivate ComDeepinDaemonAuthenticateSessionProxyPrivate;

struct _ComDeepinDaemonAuthenticateSessionProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComDeepinDaemonAuthenticateSessionProxyPrivate *priv;
};

struct _ComDeepinDaemonAuthenticateSessionProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_deepin_daemon_authenticate_session_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComDeepinDaemonAuthenticateSessionProxy, g_object_unref)
#endif

void com_deepin_daemon_authenticate_session_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComDeepinDaemonAuthenticateSession *com_deepin_daemon_authenticate_session_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComDeepinDaemonAuthenticateSession *com_deepin_daemon_authenticate_session_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_deepin_daemon_authenticate_session_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComDeepinDaemonAuthenticateSession *com_deepin_daemon_authenticate_session_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComDeepinDaemonAuthenticateSession *com_deepin_daemon_authenticate_session_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON (com_deepin_daemon_authenticate_session_skeleton_get_type ())
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComDeepinDaemonAuthenticateSessionSkeleton))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComDeepinDaemonAuthenticateSessionSkeletonClass))
#define COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON, ComDeepinDaemonAuthenticateSessionSkeletonClass))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON))
#define IS_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_SKELETON))

typedef struct _ComDeepinDaemonAuthenticateSessionSkeleton ComDeepinDaemonAuthenticateSessionSkeleton;
typedef struct _ComDeepinDaemonAuthenticateSessionSkeletonClass ComDeepinDaemonAuthenticateSessionSkeletonClass;
typedef struct _ComDeepinDaemonAuthenticateSessionSkeletonPrivate ComDeepinDaemonAuthenticateSessionSkeletonPrivate;

struct _ComDeepinDaemonAuthenticateSessionSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComDeepinDaemonAuthenticateSessionSkeletonPrivate *priv;
};

struct _ComDeepinDaemonAuthenticateSessionSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_deepin_daemon_authenticate_session_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComDeepinDaemonAuthenticateSessionSkeleton, g_object_unref)
#endif

ComDeepinDaemonAuthenticateSession *com_deepin_daemon_authenticate_session_skeleton_new (void);


G_END_DECLS

#endif /* __COM_DEEPIN_DAEMON_AUTHENTICATE_SESSION_H__ */
