/*
 * Generated by gdbus-codegen 2.58.3 from com.lingmo.daemon.Authenticate.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __COM_LINGMO_DAEMON_AUTHENTICATE_H__
#define __COM_LINGMO_DAEMON_AUTHENTICATE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.lingmo.daemon.Authenticate */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE (com_lingmo_daemon_authenticate_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE, ComLingmoDaemonAuthenticate))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE))
#define COM_LINGMO_DAEMON_AUTHENTICATE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE, ComLingmoDaemonAuthenticateIface))

struct _ComLingmoDaemonAuthenticate;
typedef struct _ComLingmoDaemonAuthenticate ComLingmoDaemonAuthenticate;
typedef struct _ComLingmoDaemonAuthenticateIface ComLingmoDaemonAuthenticateIface;

struct _ComLingmoDaemonAuthenticateIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_authenticate) (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType);

  gboolean (*handle_get_limits) (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_username);

  gboolean (*handle_pre_one_key_login) (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    gint arg_flag);

  gint  (*get_framework_state) (ComLingmoDaemonAuthenticate *object);

  const gchar * (*get_support_encrypts) (ComLingmoDaemonAuthenticate *object);

  gint  (*get_supported_flags) (ComLingmoDaemonAuthenticate *object);

  void (*limit_updated) (
    ComLingmoDaemonAuthenticate *object,
    const gchar *arg_username);

};

GType com_lingmo_daemon_authenticate_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_lingmo_daemon_authenticate_interface_info (void);
guint com_lingmo_daemon_authenticate_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_lingmo_daemon_authenticate_complete_authenticate (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *path);

void com_lingmo_daemon_authenticate_complete_get_limits (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *limits);

void com_lingmo_daemon_authenticate_complete_pre_one_key_login (
    ComLingmoDaemonAuthenticate *object,
    GDBusMethodInvocation *invocation,
    const gchar *result);



/* D-Bus signal emissions functions: */
void com_lingmo_daemon_authenticate_emit_limit_updated (
    ComLingmoDaemonAuthenticate *object,
    const gchar *arg_username);



/* D-Bus method calls: */
void com_lingmo_daemon_authenticate_call_authenticate (
    ComLingmoDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_call_authenticate_finish (
    ComLingmoDaemonAuthenticate *proxy,
    gchar **out_path,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_call_authenticate_sync (
    ComLingmoDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gint arg_authFlags,
    gint arg_appType,
    gchar **out_path,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_call_get_limits (
    ComLingmoDaemonAuthenticate *proxy,
    const gchar *arg_username,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_call_get_limits_finish (
    ComLingmoDaemonAuthenticate *proxy,
    gchar **out_limits,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_call_get_limits_sync (
    ComLingmoDaemonAuthenticate *proxy,
    const gchar *arg_username,
    gchar **out_limits,
    GCancellable *cancellable,
    GError **error);

void com_lingmo_daemon_authenticate_call_pre_one_key_login (
    ComLingmoDaemonAuthenticate *proxy,
    gint arg_flag,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lingmo_daemon_authenticate_call_pre_one_key_login_finish (
    ComLingmoDaemonAuthenticate *proxy,
    gchar **out_result,
    GAsyncResult *res,
    GError **error);

gboolean com_lingmo_daemon_authenticate_call_pre_one_key_login_sync (
    ComLingmoDaemonAuthenticate *proxy,
    gint arg_flag,
    gchar **out_result,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *com_lingmo_daemon_authenticate_get_support_encrypts (ComLingmoDaemonAuthenticate *object);
gchar *com_lingmo_daemon_authenticate_dup_support_encrypts (ComLingmoDaemonAuthenticate *object);
void com_lingmo_daemon_authenticate_set_support_encrypts (ComLingmoDaemonAuthenticate *object, const gchar *value);

gint com_lingmo_daemon_authenticate_get_framework_state (ComLingmoDaemonAuthenticate *object);
void com_lingmo_daemon_authenticate_set_framework_state (ComLingmoDaemonAuthenticate *object, gint value);

gint com_lingmo_daemon_authenticate_get_supported_flags (ComLingmoDaemonAuthenticate *object);
void com_lingmo_daemon_authenticate_set_supported_flags (ComLingmoDaemonAuthenticate *object, gint value);


/* ---- */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY (com_lingmo_daemon_authenticate_proxy_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY, ComLingmoDaemonAuthenticateProxy))
#define COM_LINGMO_DAEMON_AUTHENTICATE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY, ComLingmoDaemonAuthenticateProxyClass))
#define COM_LINGMO_DAEMON_AUTHENTICATE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY, ComLingmoDaemonAuthenticateProxyClass))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_PROXY))

typedef struct _ComLingmoDaemonAuthenticateProxy ComLingmoDaemonAuthenticateProxy;
typedef struct _ComLingmoDaemonAuthenticateProxyClass ComLingmoDaemonAuthenticateProxyClass;
typedef struct _ComLingmoDaemonAuthenticateProxyPrivate ComLingmoDaemonAuthenticateProxyPrivate;

struct _ComLingmoDaemonAuthenticateProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComLingmoDaemonAuthenticateProxyPrivate *priv;
};

struct _ComLingmoDaemonAuthenticateProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_lingmo_daemon_authenticate_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLingmoDaemonAuthenticateProxy, g_object_unref)
#endif

void com_lingmo_daemon_authenticate_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLingmoDaemonAuthenticate *com_lingmo_daemon_authenticate_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComLingmoDaemonAuthenticate *com_lingmo_daemon_authenticate_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_lingmo_daemon_authenticate_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLingmoDaemonAuthenticate *com_lingmo_daemon_authenticate_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComLingmoDaemonAuthenticate *com_lingmo_daemon_authenticate_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON (com_lingmo_daemon_authenticate_skeleton_get_type ())
#define COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON, ComLingmoDaemonAuthenticateSkeleton))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON, ComLingmoDaemonAuthenticateSkeletonClass))
#define COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON, ComLingmoDaemonAuthenticateSkeletonClass))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON))
#define IS_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LINGMO_DAEMON_AUTHENTICATE_SKELETON))

typedef struct _ComLingmoDaemonAuthenticateSkeleton ComLingmoDaemonAuthenticateSkeleton;
typedef struct _ComLingmoDaemonAuthenticateSkeletonClass ComLingmoDaemonAuthenticateSkeletonClass;
typedef struct _ComLingmoDaemonAuthenticateSkeletonPrivate ComLingmoDaemonAuthenticateSkeletonPrivate;

struct _ComLingmoDaemonAuthenticateSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComLingmoDaemonAuthenticateSkeletonPrivate *priv;
};

struct _ComLingmoDaemonAuthenticateSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_lingmo_daemon_authenticate_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLingmoDaemonAuthenticateSkeleton, g_object_unref)
#endif

ComLingmoDaemonAuthenticate *com_lingmo_daemon_authenticate_skeleton_new (void);


G_END_DECLS

#endif /* __COM_LINGMO_DAEMON_AUTHENTICATE_H__ */
