// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package charaManager

func (v *Manager) setPropDriverInfo(value string) (changed bool) {
	if v.DriverInfo != value {
		v.DriverInfo = value
		v.emitPropChangedDriverInfo(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDriverInfo(value string) error {
	return v.service.EmitPropertyChanged(v, "DriverInfo", value)
}
