// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package charaManager

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "Delete",
			Fn:     v.Delete,
			InArgs: []string{"charaType", "charaName"},
		},
		{
			Name:    "EnrollStart",
			Fn:      v.EnrollStart,
			InArgs:  []string{"driverName", "charaType", "charaName"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name: "EnrollStop",
			Fn:   v.EnrollStop,
		},
		{
			Name:    "List",
			Fn:      v.List,
			InArgs:  []string{"driverName", "charaType"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:   "Rename",
			Fn:     v.Rename,
			InArgs: []string{"charaType", "oldName", "newName"},
		},
	}
}
