// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package session

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "EncryptKey",
			Fn:      v.EncryptKey,
			InArgs:  []string{"encryptType", "encryptMethod"},
			OutArgs: []string{"encType", "encMethod", "pubKey"},
		},
		{
			Name:    "End",
			Fn:      v.End,
			InArgs:  []string{"flag"},
			OutArgs: []string{"failNum"},
		},
		{
			Name:    "GetResult",
			Fn:      v.GetResult,
			OutArgs: []string{"result"},
		},
		{
			Name: "PrivilegesDisable",
			Fn:   v.PrivilegesDisable,
		},
		{
			Name:    "PrivilegesEnable",
			Fn:      v.PrivilegesEnable,
			InArgs:  []string{"masterPath"},
			OutArgs: []string{"enabled"},
		},
		{
			Name: "Quit",
			Fn:   v.Quit,
		},
		{
			Name:   "SetQuitFlag",
			Fn:     v.SetQuitFlag,
			InArgs: []string{"method"},
		},
		{
			Name:   "SetSymmetricKey",
			Fn:     v.SetSymmetricKey,
			InArgs: []string{"key"},
		},
		{
			Name:   "SetToken",
			Fn:     v.SetToken,
			InArgs: []string{"flag", "token"},
		},
		{
			Name:    "Start",
			Fn:      v.Start,
			InArgs:  []string{"flag", "timeout"},
			OutArgs: []string{"failNum"},
		},
	}
}
