// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package session

func (v *Manager) setPropIsMFA(value bool) (changed bool) {
	if v.IsMFA != value {
		v.IsMFA = value
		v.emitPropChangedIsMFA(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedIsMFA(value bool) error {
	return v.service.EmitPropertyChanged(v, "IsMFA", value)
}

func (v *Manager) setPropPrompt(value string) (changed bool) {
	if v.Prompt != value {
		v.Prompt = value
		v.emitPropChangedPrompt(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedPrompt(value string) error {
	return v.service.EmitPropertyChanged(v, "Prompt", value)
}

func (v *Manager) setPropFactorsInfo(value []authFactor) {
	v.FactorsInfo = value
	v.emitPropChangedFactorsInfo(value)
}

func (v *Manager) emitPropChangedFactorsInfo(value []authFactor) error {
	return v.service.EmitPropertyChanged(v, "FactorsInfo", value)
}

func (v *Manager) setPropUsername(value string) (changed bool) {
	if v.Username != value {
		v.Username = value
		v.emitPropChangedUsername(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedUsername(value string) error {
	return v.service.EmitPropertyChanged(v, "Username", value)
}

func (v *Manager) setPropPINLen(value int) (changed bool) {
	if v.PINLen != value {
		v.PINLen = value
		v.emitPropChangedPINLen(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedPINLen(value int) error {
	return v.service.EmitPropertyChanged(v, "PINLen", value)
}

func (v *Manager) setPropPrgPath(value string) (changed bool) {
	if v.PrgPath != value {
		v.PrgPath = value
		v.emitPropChangedPrgPath(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedPrgPath(value string) error {
	return v.service.EmitPropertyChanged(v, "PrgPath", value)
}
