// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package face

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "DeleteFace",
			Fn:     v.DeleteFace,
			InArgs: []string{"serviceName", "username", "faceName"},
		},
		{
			Name:   "DeleteFaces",
			Fn:     v.DeleteFaces,
			InArgs: []string{"serviceName", "username"},
		},
		{
			Name:    "GetShareMemInfo",
			Fn:      v.GetShareMemInfo,
			InArgs:  []string{"id"},
			OutArgs: []string{"sockPath", "key", "size"},
		},
		{
			Name:    "ListFaces",
			Fn:      v.ListFaces,
			InArgs:  []string{"serviceName", "username"},
			OutArgs: []string{"faces"},
		},
		{
			Name:   "RenameFace",
			Fn:     v.RenameFace,
			InArgs: []string{"serviceName", "username", "oldFace", "newFace"},
		},
		{
			Name:   "SetDefaultDevice",
			Fn:     v.SetDefaultDevice,
			InArgs: []string{"serviceName", "device"},
		},
		{
			Name:   "SetDefaultService",
			Fn:     v.SetDefaultService,
			InArgs: []string{"serviceName"},
		},
		{
			Name:    "StartEnroll",
			Fn:      v.StartEnroll,
			InArgs:  []string{"username", "serviceName", "faceName"},
			OutArgs: []string{"id"},
		},
		{
			Name:    "StartVerify",
			Fn:      v.StartVerify,
			InArgs:  []string{"username", "serviceName", "timeout"},
			OutArgs: []string{"id"},
		},
		{
			Name:   "StopEnroll",
			Fn:     v.StopEnroll,
			InArgs: []string{"id"},
		},
		{
			Name:   "StopVerify",
			Fn:     v.StopVerify,
			InArgs: []string{"id"},
		},
	}
}
