// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package face

func (v *Manager) setPropDefaultDevice(value string) (changed bool) {
	if v.DefaultDevice != value {
		v.DefaultDevice = value
		v.emitPropChangedDefaultDevice(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDefaultDevice(value string) error {
	return v.service.EmitPropertyChanged(v, "DefaultDevice", value)
}

func (v *Manager) setPropDefaultService(value string) (changed bool) {
	if v.DefaultService != value {
		v.DefaultService = value
		v.emitPropChangedDefaultService(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDefaultService(value string) error {
	return v.service.EmitPropertyChanged(v, "DefaultService", value)
}

func (v *Manager) setPropServiceList(value string) (changed bool) {
	if v.ServiceList != value {
		v.ServiceList = value
		v.emitPropChangedServiceList(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedServiceList(value string) error {
	return v.service.EmitPropertyChanged(v, "ServiceList", value)
}
