// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package authenticate

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "Authenticate",
			Fn:      v.Authenticate,
			InArgs:  []string{"username", "authFlags", "appType"},
			OutArgs: []string{"result"},
		},
		{
			Name:    "GetLimits",
			Fn:      v.GetLimits,
			InArgs:  []string{"username"},
			OutArgs: []string{"limitsInfo"},
		},
		{
			Name:    "PreOneKeyLogin",
			Fn:      v.PreOneKeyLogin,
			InArgs:  []string{"flag"},
			OutArgs: []string{"username"},
		},
		{
			Name:   "ResetLimits",
			Fn:     v.ResetLimits,
			InArgs: []string{"username"},
		},
	}
}
