// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package fingerprint

import (
	"github.com/LingmoOS/golang-github-lingmo-go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "Claim",
			Fn:     v.Claim,
			InArgs: []string{"username", "claimed"},
		},
		{
			Name:   "DeleteAllFingers",
			Fn:     v.DeleteAllFingers,
			InArgs: []string{"username"},
		},
		{
			Name:   "DeleteFinger",
			Fn:     v.DeleteFinger,
			InArgs: []string{"username", "finger"},
		},
		{
			Name:   "Enroll",
			Fn:     v.Enroll,
			InArgs: []string{"finger"},
		},
		{
			Name:    "ListFingers",
			Fn:      v.ListFingers,
			InArgs:  []string{"username"},
			OutArgs: []string{"fingers"},
		},
		{
			Name: "PreAuthEnroll",
			Fn:   v.PreAuthEnroll,
		},
		{
			Name:   "RenameFinger",
			Fn:     v.RenameFinger,
			InArgs: []string{"username", "finger", "newName"},
		},
		{
			Name:   "SetDefaultDevice",
			Fn:     v.SetDefaultDevice,
			InArgs: []string{"deviceName"},
		},
		{
			Name: "StopEnroll",
			Fn:   v.StopEnroll,
		},
		{
			Name: "StopVerify",
			Fn:   v.StopVerify,
		},
		{
			Name:   "Verify",
			Fn:     v.Verify,
			InArgs: []string{"finger"},
		},
	}
}
