// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package fingerprint

func (v *Manager) setPropDefaultDevice(value string) (changed bool) {
	if v.DefaultDevice != value {
		v.DefaultDevice = value
		v.emitPropChangedDefaultDevice(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDefaultDevice(value string) error {
	return v.service.EmitPropertyChanged(v, "DefaultDevice", value)
}

func (v *Manager) setPropDevices(value string) (changed bool) {
	if v.Devices != value {
		v.Devices = value
		v.emitPropChangedDevices(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDevices(value string) error {
	return v.service.EmitPropertyChanged(v, "Devices", value)
}
