// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package ukey

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "ConstructVerification",
			Fn:      v.ConstructVerification,
			InArgs:  []string{"serviceName", "username", "useDefaultService"},
			OutArgs: []string{"id"},
		},
		{
			Name:    "GetPINLength",
			Fn:      v.GetPINLength,
			InArgs:  []string{"serviceName", "username", "useDefaultDevice"},
			OutArgs: []string{"length"},
		},
		{
			Name:    "GetUserList",
			Fn:      v.GetUserList,
			InArgs:  []string{"serviceName", "useDefaultDevice"},
			OutArgs: []string{"users"},
		},
		{
			Name:   "SetDefaultDevice",
			Fn:     v.SetDefaultDevice,
			InArgs: []string{"device"},
		},
		{
			Name:   "SetPin",
			Fn:     v.SetPin,
			InArgs: []string{"id", "pin"},
		},
		{
			Name:   "SetSessionPath",
			Fn:     v.SetSessionPath,
			InArgs: []string{"id"},
		},
		{
			Name:   "StartVerify",
			Fn:     v.StartVerify,
			InArgs: []string{"id"},
		},
		{
			Name:   "StopVerify",
			Fn:     v.StopVerify,
			InArgs: []string{"id"},
		},
	}
}
