// Code generated by "dbusutil-gen -type Manager manager.go -output ukey_dbusutil.go"; DO NOT EDIT.

package ukey

func (v *Manager) setPropValidDevices(value string) (changed bool) {
	if v.ValidDevices != value {
		v.ValidDevices = value
		v.emitPropChangedValidDevices(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedValidDevices(value string) error {
	return v.service.EmitPropertyChanged(v, "ValidDevices", value)
}

func (v *Manager) setPropDefaultDevice(value string) (changed bool) {
	if v.DefaultDevice != value {
		v.DefaultDevice = value
		v.emitPropChangedDefaultDevice(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedDefaultDevice(value string) error {
	return v.service.EmitPropertyChanged(v, "DefaultDevice", value)
}
